In [85]:
import pandas as pd
import numpy as np
descriptions = pd.read_excel("multi_asset_etf_data.xlsx", "descriptions")
prices = pd.read_excel("multi_asset_etf_data.xlsx", "prices")
total_returns = pd.read_excel("multi_asset_etf_data.xlsx", "total returns")
excess_returns = pd.read_excel("multi_asset_etf_data.xlsx", "excess returns")

In [86]:
import warnings
warnings.filterwarnings("ignore")

In [87]:
descriptions

,ticker,shortName,quoteType,currency,volume,totalAssets,longBusinessSummary
0,SPY,SPDR S&P 500,ETF,USD,48833086,566341992448,The Trust seeks to achieve its investment obje...
1,EFA,iShares MSCI EAFE ETF,ETF,USD,11332778,57923706880,The fund generally will invest at least 80% of...
2,EEM,iShares MSCI Emerging Index Fun,ETF,USD,23583292,17685696512,The fund generally will invest at least 80% of...
3,PSP,Invesco Global Listed Private E,ETF,USD,9989,248054672,The fund generally will invest at least 90% of...
4,QAI,NYLI Hedge Multi-Strategy Track,ETF,USD,66176,574961600,"The fund is a ""fund of funds"" which means it i..."
5,HYG,iShares iBoxx $ High Yield Corp,ETF,USD,31335696,16903942144,The underlying index is a rules-based index co...
6,DBC,Invesco DB Commodity Index Trac,ETF,USD,816794,1496658176,The fund pursues its investment objective by i...
7,IYR,iShares U.S. Real Estate ETF,ETF,USD,3310338,4560725504,The fund seeks to track the investment results...
8,IEF,iShares 7-10 Year Treasury Bond,ETF,USD,7913316,31752601600,The underlying index measures the performance ...
9,BWX,SPDR Bloomberg International Tr,ETF,USD,138010,1028062656,"The fund generally invests substantially all, ..."
10,TIP,iShares TIPS Bond ETF,ETF,USD,2373593,18455549952,The index tracks the performance of inflation-...
11,SHV,iShares Short Treasury Bond ETF,ETF,USD,10162795,19172577280,The fund will invest at least 80% of its asset...

In [5]:
prices

,Date,BWX,DBC,EEM,EFA,HYG,IEF,IYR,PSP,QAI,SHV,SPY,TIP
0,2011-01-31,24.712528,26.263178,34.413433,39.687977,43.000534,71.497787,36.436028,22.837017,22.742193,94.590927,99.931030,76.467964
1,2011-02-28,24.876053,27.358627,34.398407,41.096821,43.617771,71.348801,38.083073,23.753832,22.800936,94.599472,103.402359,77.019150
2,2011-03-31,25.085691,28.085859,36.561928,40.115311,43.636265,71.238472,37.666645,24.149742,22.926815,94.615799,103.414780,77.935883
3,2011-04-30,26.310003,29.365417,37.561058,42.372135,44.333401,72.550133,39.423157,25.566628,23.363194,94.667252,106.409813,79.789200
4,2011-05-31,25.953600,27.846518,36.456760,41.437351,44.392467,74.367989,39.822655,24.503958,23.363194,94.657852,105.216507,80.001373
...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,2024-05-31,21.530746,23.270000,41.503429,79.787514,75.607361,91.692085,85.528976,61.688713,30.930000,108.621712,524.066650,105.341492
161,2024-06-30,21.326733,23.230000,42.590000,78.330002,75.969795,92.807968,87.133812,60.633411,31.030001,109.077744,542.555786,106.143684
162,2024-07-31,22.148066,22.580000,42.950001,80.360001,77.756790,95.496819,93.777596,64.792091,31.379999,109.579361,549.125671,107.977242
163,2024-08-31,22.823999,22.110001,43.369999,82.980003,78.959991,96.781998,98.842354,64.871498,31.620001,110.125000,561.956299,108.840004
164,2024-09-30,23.459999,22.320000,46.610001,83.919998,80.360001,98.389999,101.150002,68.529999,32.090000,110.629997,571.469971,110.540001

In [88]:
total_returns

,Date,BWX,DBC,EEM,EFA,HYG,IEF,IYR,PSP,QAI,SHV,SPY,TIP
0,2011-02-28,0.006617,0.041710,-0.000437,0.035498,0.014354,-0.002084,0.045204,0.040146,0.002583,0.000090,0.034737,0.007208
1,2011-03-31,0.008427,0.026581,0.062896,-0.023883,0.000424,-0.001546,-0.010935,0.016667,0.005521,0.000173,0.000120,0.011903
2,2011-04-30,0.048805,0.045559,0.027327,0.056258,0.015976,0.018412,0.046633,0.058671,0.019034,0.000544,0.028961,0.023780
3,2011-05-31,-0.013546,-0.051724,-0.029400,-0.022061,0.001332,0.025057,0.010134,-0.041565,0.000000,-0.000099,-0.011214,0.002659
4,2011-06-30,-0.000097,-0.042645,-0.009355,-0.012107,-0.005706,-0.005044,-0.031060,-0.042581,-0.010776,0.000173,-0.016870,0.007549
...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,2024-05-31,0.014228,-0.002999,0.019517,0.050602,0.016339,0.018001,0.049274,0.039039,0.013434,0.004582,0.050580,0.017771
160,2024-06-30,-0.009475,-0.001719,0.026180,-0.018267,0.004794,0.012170,0.018764,-0.017107,0.003233,0.004198,0.035280,0.007615
161,2024-07-31,0.038512,-0.027981,0.008453,0.025916,0.023522,0.028972,0.076248,0.068587,0.011279,0.004599,0.012109,0.017274
162,2024-08-31,0.030519,-0.020815,0.009779,0.032603,0.015474,0.013458,0.054008,0.001226,0.007648,0.004979,0.023366,0.007990
163,2024-09-30,0.027865,0.009498,0.074706,0.011328,0.017731,0.016615,0.023347,0.056396,0.014864,0.004586,0.016930,0.015619

In [89]:
excess_returns

,Date,BWX,DBC,EEM,EFA,HYG,IEF,IYR,PSP,QAI,SPY,TIP
0,2011-02-28,0.006527,0.041620,-0.000527,0.035408,0.014264,-0.002174,0.045113,0.040056,0.002493,0.034647,0.007118
1,2011-03-31,0.008255,0.026409,0.062723,-0.024055,0.000251,-0.001719,-0.011107,0.016495,0.005348,-0.000052,0.011730
2,2011-04-30,0.048261,0.045015,0.026783,0.055715,0.015432,0.017868,0.046089,0.058127,0.018490,0.028418,0.023236
3,2011-05-31,-0.013447,-0.051625,-0.029301,-0.021962,0.001432,0.025156,0.010233,-0.041465,0.000099,-0.011115,0.002758
4,2011-06-30,-0.000270,-0.042817,-0.009528,-0.012280,-0.005878,-0.005217,-0.031233,-0.042754,-0.010948,-0.017042,0.007377
...,...,...,...,...,...,...,...,...,...,...,...,...
159,2024-05-31,0.009647,-0.007581,0.014935,0.046020,0.011758,0.013420,0.044692,0.034457,0.008852,0.045998,0.013189
160,2024-06-30,-0.013674,-0.005917,0.021982,-0.022466,0.000595,0.007972,0.014565,-0.021305,-0.000965,0.031082,0.003417
161,2024-07-31,0.033913,-0.032580,0.003854,0.021317,0.018924,0.024373,0.071649,0.063989,0.006681,0.007510,0.012676
162,2024-08-31,0.025539,-0.025794,0.004799,0.027624,0.010495,0.008478,0.049029,-0.003754,0.002669,0.018386,0.003011
163,2024-09-30,0.023280,0.004912,0.070120,0.006742,0.013145,0.012029,0.018761,0.051810,0.010278,0.012344,0.011034

In [90]:
# Summary Statistics
# Calculate and display the mean and volatility of each asset’s excess return. (Recall we use volatility to refer to standard deviation.)
result_1 = pd.DataFrame(excess_returns.mean()*12, columns=['mean'])
result_1['volatility'] = excess_returns.std()*np.sqrt(12)

In [91]:
result_1

         mean volatility
BWX -0.011888   0.081671
DBC -0.009086   0.168455
EEM  0.026960    0.17994
EFA  0.055037   0.152203
HYG  0.037356   0.077289
IEF  0.013939   0.063197
IYR  0.077912   0.169585
PSP  0.092851   0.215238
QAI  0.014959   0.049007
SPY  0.126983   0.143066
TIP  0.016844   0.051258

In [92]:
# Which assets have the best and worst Sharpe ratios? Recall that the Sharpe Ratio is simply the ratio of the mean-to-volatility of excess return
result_1['Sharpe ratio']=result_1['mean']/result_1['volatility']
max_sharpe_ratio = result_1['Sharpe ratio'].max()
max_sharpe_ratio_asset = result_1.loc[result_1['Sharpe ratio']==max_sharp_ratio].index[0]
max_sharpe_ratio_asset

'SPY'

In [93]:
max_sharpe_ratio

0.8875780193539925

In [94]:
# Descriptive Analysis
# Calculate the correlation matrix of the returns. Which pair has the highest correlation? And the lowest?
correlation_matrix = excess_returns.corr()
correlation_matrix

,BWX,DBC,EEM,EFA,HYG,IEF,IYR,PSP,QAI,SPY,TIP
BWX,1.000000,0.233222,0.638705,0.600620,0.620946,0.568903,0.562599,0.552010,0.662425,0.466152,0.680001
DBC,0.233222,1.000000,0.516908,0.521447,0.471924,-0.300523,0.290040,0.467111,0.494467,0.448389,0.114379
EEM,0.638705,0.516908,1.000000,0.820770,0.694174,0.020477,0.589003,0.761796,0.791130,0.699939,0.379465
EFA,0.600620,0.521447,0.820770,1.000000,0.790742,0.018537,0.705926,0.910596,0.863957,0.864822,0.386677
HYG,0.620946,0.471924,0.694174,0.790742,1.000000,0.180087,0.739567,0.814182,0.811161,0.794782,0.541758
IEF,0.568903,-0.300523,0.020477,0.018537,0.180087,1.000000,0.297047,0.017486,0.176287,-0.005053,0.745025
IYR,0.562599,0.290040,0.589003,0.705926,0.739567,0.297047,1.000000,0.753810,0.718397,0.760646,0.590805
PSP,0.552010,0.467111,0.761796,0.910596,0.814182,0.017486,0.753810,1.000000,0.870673,0.890719,0.415854
QAI,0.662425,0.494467,0.791130,0.863957,0.811161,0.176287,0.718397,0.870673,1.000000,0.862479,0.527724
SPY,0.466152,0.448389,0.699939,0.864822,0.794782,-0.005053,0.760646,0.890719,0.862479,1.000000,0.393647
TIP,0.680001,0.114379,0.379465,0.386677,0.541758,0.745025,0.590805,0.415854,0.527724,0.393647,1.000000

In [95]:
correlations = correlation_matrix.unstack()
correlations = correlations[correlations.index.get_level_values(0) != correlations.index.get_level_values(1)] # filter out self-correlations
max_correlation = correlations.idxmax(), correlations.max()
min_correlation = correlations.idxmin(), correlations.min()
print('pair has the highest correlation,',max_correlation[0])
print('pair has the highest correlation,',min_correlation[0])

pair has the highest correlation, ('EFA', 'PSP')
pair has the highest correlation, ('DBC', 'IEF')

In [96]:
# How well have TIPS done in our sample? Have they outperformed domestic bonds? Foreign bonds?
correlation_matrix[correlation_matrix.index == 'TIP']

,BWX,DBC,EEM,EFA,HYG,IEF,IYR,PSP,QAI,SPY,TIP
TIP,0.680001,0.114379,0.379465,0.386677,0.541758,0.745025,0.590805,0.415854,0.527724,0.393647,1.0

In [97]:
result_1[result_1.index.isin(['TIP','BWX','IEF'])]

         mean volatility Sharpe ratio
BWX -0.011888   0.081671    -0.145563
IEF  0.013939   0.063197     0.220561
TIP  0.016844   0.051258     0.328618

In [98]:
# 2.3 The MV frontier

# Compute and display the weights of the tangency portfolios:  w^tan
def return_tangent_weights(returns):
    cov = returns.cov()
    cov_inv = np.linalg.inv(cov*12) # compute the inverse of a square matrix
    mu = returns.mean()*12

    ones = np.ones(returns.columns[1:].shape)
    scaling = 1/(np.transpose(ones) @ cov_inv @ mu)
    tangent_return = scaling*(cov_inv @ mu)
    tangent_weights = pd.DataFrame(index = returns.columns[1:], data = tangent_return, columns = ['Tangent Weights'])
    return tangent_weights

tangent_weights = return_tangent_weights(excess_returns)
tangent_weights

     Tangent Weights
BWX         2.730253
DBC        -0.111241
EEM        -0.615698
EFA         0.530692
HYG        -0.832578
IEF        -4.682480
IYR         0.877108
PSP         0.277002
QAI         7.220592
SPY        -4.904086
TIP         0.510436

In [99]:
# Does the ranking of weights align with the ranking of Sharpe ratios?
compare = tangent_weights.merge(result_1['Sharpe ratio'], on=tangent_weights.index).rename(columns={'key_0':'assets'}).set_index('assets')
print(compare)
print("The ranking of weights does not align with the ranking of Sharpe ratios")

        Tangent Weights Sharpe ratio
assets
BWX            2.730253    -0.145563
DBC           -0.111241    -0.053935
EEM           -0.615698     0.149829
EFA            0.530692     0.361605
HYG           -0.832578     0.483335
IEF           -4.682480     0.220561
IYR            0.877108     0.459426
PSP            0.277002     0.431386
QAI            7.220592     0.305241
SPY           -4.904086     0.887578
TIP            0.510436     0.328618
The ranking of weights does not align with the ranking of Sharpe ratios

In [100]:
# Compute the mean, volatility, and Sharpe ratio for the tangency portfolio corresponding to  w^tan
excess_returns_1 = excess_returns[excess_returns.columns[1:]]
w_t_result = excess_returns_1@tangent_weights
w_t_stats = pd.DataFrame(index=w_t_result.columns)
w_t_stats['mean'] = w_t_result.mean()*12
w_t_stats['volatility'] = w_t_result.std()*np.sqrt(12)
w_t_stats['Sharpe ratio'] = (w_t_stats['mean']/w_t_stats['volatility'])*np.sqrt(12)
w_t_stats

                     mean  volatility  Sharpe ratio
Tangent Weights -0.527276    0.328513      -5.56001

In [101]:
# 2.4 TIPS

# Assess how much the tangency portfolio (and performance) change if...
#(1)TIPS are dropped completely from the investment set.
w_t_without_TIPS = return_tangent_weights(excess_returns.drop(columns=['TIP']))
w_t_without_TIPS

     Tangent Weights
BWX         3.015911
DBC        -0.090968
EEM        -0.664230
EFA         0.540606
HYG        -0.871637
IEF        -4.832385
IYR         0.990156
PSP         0.324898
QAI         7.976911
SPY        -5.389260

In [102]:
#(2)The expected excess return to TIPS is adjusted to be 0.0012 higher than what the historic sample shows.
TIP_new = 0.0012
excess_returns_adj = excess_returns.copy()
excess_returns_adj['TIP'] += TIP_new
w_t_adj_TIPS = return_tangent_weights(excess_returns_adj)
w_t_adj_TIPS

     Tangent Weights
BWX        29.260095
DBC         1.771624
EEM        -5.123028
EFA         1.451443
HYG        -4.460119
IEF       -18.604613
IYR        11.376147
PSP         4.725247
QAI        77.462118
SPY       -49.963644
TIP       -46.895270

In [103]:
# 3. Allocations

def return_reg_tangent_weights(returns):
    p = 0.5
    cov = returns.cov()
    cov_mat_diag = np.diag(np.diag(cov))
    cov_mat = p*cov + p*cov_mat_diag
    cov_inv = np.linalg.inv(cov_mat*12) # compute the inverse of a square matrix

    ones = np.ones(returns.columns[1:].shape)
    mu = returns.mean()*12
    scaling = 1/(np.transpose(ones) @ cov_inv @ mu)
    tangent_return = scaling*(cov_inv @ mu)
    tangent_weights = pd.DataFrame(index = returns.columns[1:], data = tangent_return, columns = ['Tangent Weights'])
    return tangent_weights


target_mean = 0.01
excess_returns_3 = excess_returns[excess_returns.columns[1:]]
w_t_compare = pd.DataFrame(index = excess_returns_3.columns, columns =
                           ['tangency','tangency with TIPS dropped',
                            'tangency with TIPS adjusted','equally-weighted',
                            'risk-parity','regularized'])
w_t_without_TIPS.loc['TIP']=0
w_t_compare['tangency'] = tangent_weights
w_t_compare['tangency with TIPS dropped'] = w_t_without_TIPS
w_t_compare['tangency with TIPS adjusted'] = w_t_adj_TIPS
w_t_compare['equally-weighted'] = 1/len(excess_returns.columns)
w_t_compare['risk-parity'] = 1/excess_returns.var()
w_t_compare['regularized'] = return_reg_tangent_weights(excess_returns)
w_t_compare

,tangency,tangency with TIPS dropped,tangency with TIPS adjusted,equally-weighted,risk-parity,regularized
BWX,2.730253,3.015911,29.260095,0.083333,1799.053371,-0.855638
DBC,-0.111241,-0.090968,1.771624,0.083333,422.875611,-0.172547
EEM,-0.615698,-0.664230,-5.123028,0.083333,370.618768,-0.083825
EFA,0.530692,0.540606,1.451443,0.083333,518.006421,0.047259
HYG,-0.832578,-0.871637,-4.460119,0.083333,2008.858587,0.401333
IEF,-4.682480,-4.832385,-18.604613,0.083333,3004.653551,0.498538
IYR,0.877108,0.990156,11.376147,0.083333,417.261797,0.101704
PSP,0.277002,0.324898,4.725247,0.083333,259.026648,0.062771
QAI,7.220592,7.976911,77.462118,0.083333,4996.546298,-0.198272
SPY,-4.904086,-5.389260,-49.963644,0.083333,586.280583,0.790188
TIP,0.510436,0.000000,-46.895270,0.083333,4567.352009,0.408489

In [104]:
w_t_3 = w_t_compare*target_mean/(excess_returns.mean()@w_t_compare)
w_t_3

,tangency,tangency with TIPS dropped,tangency with TIPS adjusted,equally-weighted,risk-parity,regularized
BWX,-0.621364,-0.623116,-0.638550,0.271575,0.522879,-0.675374
DBC,0.025317,0.018795,-0.038663,0.271575,0.122905,-0.136195
EEM,0.140124,0.137236,0.111801,0.271575,0.107717,-0.066165
EFA,-0.120777,-0.111694,-0.031675,0.271575,0.150554,0.037302
HYG,0.189482,0.180089,0.097334,0.271575,0.583857,0.316781
IEF,1.065661,0.998417,0.406013,0.271575,0.873276,0.393506
IYR,-0.199617,-0.204576,-0.248264,0.271575,0.121273,0.080277
PSP,-0.063041,-0.067127,-0.103120,0.271575,0.075284,0.049547
QAI,-1.643297,-1.648106,-1.690473,0.271575,1.452202,-0.156500
SPY,1.116095,1.113473,1.090368,0.271575,0.170397,0.623712
TIP,-0.116167,-0.000000,1.023406,0.271575,1.327461,0.322429

In [105]:
excess_returns_1 = excess_returns[excess_returns.columns[1:]]
w_t_result = excess_returns_1@w_t_3
w_t_stats = pd.DataFrame(index=w_t_result.columns)
w_t_stats['mean'] = w_t_result.mean()*12
w_t_stats['volatility'] = w_t_result.std()*np.sqrt(12)
w_t_stats['Sharpe ratio'] = (w_t_stats['mean']/w_t_stats['volatility'])*np.sqrt(12)
w_t_stats

                             mean  volatility  Sharpe ratio
tangency                     0.12    0.074765      5.560010
tangency with TIPS dropped   0.12    0.074818      5.556008
tangency with TIPS adjusted  0.12    0.079781      5.210440
equally-weighted             0.12    0.291527      1.425912
risk-parity                  0.12    0.309515      1.343044
regularized                  0.12    0.102604      4.051409